/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ngexotubyrocdiunzgfy"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5nZXhvdHVieXJvY2RpdW56Z2Z5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODcwMjQ0NDYsImV4cCI6MjEwMjYwMDQ0Nn0.J-Glyxdb5uIM8uFQphQ3meRaymKQMOuB-62L7pYDams"